[PHP]
; Utile ? C'est déjà la valeur par défaut
engine = On
; Utile ? C'est déjà la valeur par défaut
short_open_tag = Off
asp_tags = Off
; Utile ? C'est déjà la valeur par défaut
precision = 14
; Utile ? C'est déjà la valeur par défaut
output_buffering = 4096
; Utile ? C'est déjà la valeur par défaut
zlib.output_compression = Off
; Utile ? C'est déjà la valeur par défaut
implicit_flush = Off
; Utile ? C'est déjà la valeur par défaut
unserialize_callback_func =
serialize_precision = 17
disable_functions = system,popen,show_source
; Utile ? C'est déjà la valeur par défaut
disable_classes =
; Utile ? C'est déjà la valeur par défaut
zend.enable_gc = On
expose_php = Off
; Voir si on peut réduire ce paramètre
max_execution_time = 90
max_input_time = 30
memory_limit = 512M
; memory_limit = 128M
; Plutôt mettre E_ALL ? Sémantiquement plus correct
error_reporting = -1
display_errors = On
display_startup_errors = On
log_errors = On
; Utile ? C'est déjà la valeur par défaut
log_errors_max_len = 1024
; Utile ? C'est déjà la valeur par défaut
ignore_repeated_errors = Off
; Utile ? C'est déjà la valeur par défaut
ignore_repeated_source = Off
; Utile ? C'est déjà la valeur par défaut
report_memleaks = On
; Utile ? C'est déjà la valeur par défaut
html_errors = On
; Utile ? C'est déjà la valeur par défaut
variables_order = "GPCS"
; Utile ? C'est déjà la valeur par défaut
request_order = "GP"
; Utile ? C'est déjà la valeur par défaut
register_argc_argv = Off
; Utile ? C'est déjà la valeur par défaut
auto_globals_jit = On
; Utile ? C'est déjà la valeur par défaut
auto_prepend_file =
; Utile ? C'est déjà la valeur par défaut
auto_append_file =
; Utile ? C'est déjà la valeur par défaut
default_mimetype = "text/html"
; Utile ? C'est déjà la valeur par défaut
doc_root =
; Utile ? C'est déjà la valeur par défaut
user_dir =
; Utile ? C'est déjà la valeur par défaut
enable_dl = Off
; Utile ? C'est déjà la valeur par défaut
file_uploads = On
upload_max_filesize = 30M
max_file_uploads = 3
; Utile ? C'est déjà la valeur par défaut
allow_url_fopen = On
; Utile ? C'est déjà la valeur par défaut
allow_url_include = Off
default_socket_timeout = 3
post_max_size=30M
max_input_vars=5000

[Opcache]
; Utile ? C'est déjà la valeur par défaut
opcache.memory_consumption=128
; Utile ? C'est déjà la valeur par défaut
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.fast_shutdown=1
opcache.enable_cli=1

[CLI Server]
; Utile ? C'est déjà la valeur par défaut
cli_server.color = On

[Date]
date.timezone = Europe/Paris

[Pdo_mysql]
pdo_mysql.allow_local_infile = On
pdo_mysql.allow_persistent = On
pdo_mysql.cache_size = 2000
pdo_mysql.max_persistent = -1
pdo_mysql.max_links = -1
pdo_mysql.default_port = 3306
pdo_mysql.default_host =
pdo_mysql.default_user =
pdo_mysql.default_password =
pdo_mysql.connect_timeout = 60
pdo_mysql.trace_mode = Off

[SQL]
sql.safe_mode = On

[Interbase]
; Utile ? C'est déjà la valeur par défaut
ibase.allow_persistent = 1
; Utile ? C'est déjà la valeur par défaut
ibase.max_persistent = -1
; Utile ? C'est déjà la valeur par défaut
ibase.max_links = -1
; Utile ? C'est déjà la valeur par défaut
ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
; Utile ? C'est déjà la valeur par défaut
ibase.dateformat = "%Y-%m-%d"
; Utile ? C'est déjà la valeur par défaut
ibase.timeformat = "%H:%M:%S"

[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.cache_size = 2000
; Utile ? C'est déjà la valeur par défaut
mysqli.default_port = 3306
; Utile ? C'est déjà la valeur par défaut
mysqli.default_host =
; Utile ? C'est déjà la valeur par défaut
mysqli.default_user =
; Utile ? C'est déjà la valeur par défaut
mysqli.default_pw =
; Utile ? C'est déjà la valeur par défaut
mysqli.reconnect = Off

[mysqlnd]
mysqlnd.collect_statistics = Off
; Utile ? C'est déjà la valeur par défaut
mysqlnd.collect_memory_statistics = Off

; Utile ? C'est déjà la valeur par défaut
[bcmath]
bcmath.scale = 0

[Session]
session.save_handler = files
session.save_path = /home/prv/cache
session.use_cookies = 1
session.use_only_cookies = 1
session.name = prv
session.auto_start = 0
session.cookie_lifetime =
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly = On
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 100
session.gc_maxlifetime = 86400
session.bug_compat_42 = On
session.bug_compat_warn = On
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.hash_function = 0
session.hash_bits_per_character = 5
url_rewriter.tags = "a=href,area=href,frame=src,input=src,form=fakeentry"